/* Generated By:JJTree: Do not edit this line. WikiParserTreeConstants.java */

package org.wyona.wiki;

public interface WikiParserTreeConstants
{
  public int JJTWIKIBODY = 0;
  public int JJTPARAGRAPH = 1;
  public int JJTBOLD = 2;
  public int JJTITALIC = 3;
  public int JJTUNDERLINE = 4;
  public int JJTTABLE = 5;
  public int JJTTABLEROW = 6;
  public int JJTTABLECOL = 7;
  public int JJTLIST = 8;
  public int JJTPLAIN = 9;
  public int JJTPLAINTEXT = 10;
  public int JJTHRULE = 11;
  public int JJTTITLE = 12;
  public int JJTTEXT = 13;
  public int JJTFORCENEWLINE = 14;


  public String[] jjtNodeName = {
    "WikiBody",
    "Paragraph",
    "Bold",
    "Italic",
    "Underline",
    "Table",
    "TableRow",
    "TableCol",
    "List",
    "Plain",
    "PlainText",
    "Hrule",
    "Title",
    "Text",
    "ForceNewline",
  };
}
