/* Generated By:JJTree&JavaCC: Do not edit this line. WikiParserConstants.java */
package org.wyona.wiki;

public interface WikiParserConstants {

  int EOF = 0;
  int BOLD = 1;
  int ITALIC = 2;
  int UNDERLINE = 3;
  int NOTAGS_EOL = 4;
  int NOTAGS_BOLD = 5;
  int NOTAGS_ITALIC = 6;
  int NOTAGS_UNDERLINE = 7;
  int NOTAGS_FORCE_NEWLINE = 8;
  int NOTAGS_ANY_CHAR = 9;
  int HRULE = 10;
  int TABLE = 11;
  int TABLE_EOL = 12;
  int TABLE_TABLE = 13;
  int TABLE_BOLD = 14;
  int TABLE_ITALIC = 15;
  int TABLE_UNDERLINE = 16;
  int TABLE_FORCE_NEWLINE = 17;
  int TABLE_ANY_CHAR = 18;
  int LIST = 19;
  int LIST_EOL = 20;
  int LIST_LIST = 21;
  int LIST_BOLD = 22;
  int LIST_ITALIC = 23;
  int LIST_UNDERLINE = 24;
  int LIST_FORCE_NEWLINE = 25;
  int LIST_ANY_CHAR = 26;
  int TITLE = 27;
  int TITLE_EOL = 28;
  int TITLE_BOLD = 29;
  int TITLE_ITALIC = 30;
  int TITLE_UNDERLINE = 31;
  int TITLE_FORCE_NEWLINE = 32;
  int TITLE_ANY_CHAR = 33;
  int START_PLAIN = 34;
  int END_PLAIN = 35;
  int PLAIN_ANY_CHAR = 36;
  int FORCE_NEWLINE = 37;
  int TAB = 38;
  int EOL = 39;
  int ANY_CHAR = 40;

  int DEFAULT = 0;
  int DEFAULT_NOTAGS = 1;
  int IN_TABLE = 2;
  int IN_LIST = 3;
  int IN_TITLE = 4;
  int IN_PLAIN = 5;

  String[] tokenImage = {
    "<EOF>",
    "\"__\"",
    "\"\\\'\\\'\"",
    "\"^^\"",
    "<NOTAGS_EOL>",
    "<NOTAGS_BOLD>",
    "<NOTAGS_ITALIC>",
    "<NOTAGS_UNDERLINE>",
    "<NOTAGS_FORCE_NEWLINE>",
    "<NOTAGS_ANY_CHAR>",
    "\"---\"",
    "\"|\"",
    "<TABLE_EOL>",
    "\"|\"",
    "<TABLE_BOLD>",
    "<TABLE_ITALIC>",
    "<TABLE_UNDERLINE>",
    "<TABLE_FORCE_NEWLINE>",
    "<TABLE_ANY_CHAR>",
    "\"*\"",
    "<LIST_EOL>",
    "<LIST_LIST>",
    "<LIST_BOLD>",
    "<LIST_ITALIC>",
    "<LIST_UNDERLINE>",
    "<LIST_FORCE_NEWLINE>",
    "<LIST_ANY_CHAR>",
    "\"!\"",
    "<TITLE_EOL>",
    "<TITLE_BOLD>",
    "<TITLE_ITALIC>",
    "<TITLE_UNDERLINE>",
    "<TITLE_FORCE_NEWLINE>",
    "<TITLE_ANY_CHAR>",
    "\"{{\"",
    "\"}}\"",
    "<PLAIN_ANY_CHAR>",
    "\"//\"",
    "\"\\t\"",
    "<EOL>",
    "<ANY_CHAR>",
  };

}
